app_web_login:
  path:     /login
  controller: App\Controller\Web\UserController::login
app_web_logout:
  path:     /logout
  controller: App\Controller\Web\UserController::logout
app_web_player:
  prefix: /player
  resource: './app_web_player.yaml'
app_web_location:
  prefix: /location
  resource: './app_web_location.yaml'
