index:
  path: /
  defaults: { _controller: App\Controller\PublicController::index }
app_api:
  prefix: /api
  resource: '../config/routes/app_api.yaml'
app_web:
  prefix: /web
  resource: '../config/routes/app_web.yaml'